#!/bin/sh

usage="gazlookup-plplus <input.xml >output.xml"
descr="Do Unlock-Pleiades+ gazetteer lookup on a set of placenames."

unlock_host='http://unlock.edina.ac.uk'

. `dirname $0`/setup

while [ $# -gt 0 ]; do
  arg=$1
  shift
  case $arg in
    *)
      echo "usage: $usage" >&2
      exit 2
  esac
done

lib=$here/lib/georesolve

cat >$tmp-input

lxt -s $lib/dounlockquery.xsl -p host "$unlock_host" -p gazetteer "plplus" <$tmp-input


